"""risley_lattice -- frequency-lattice inversion of Risley prism systems.

The scan pattern's analytic signal z = x + iy is quasi-periodic on the
integer lattice generated by the SIGNED prism speeds. This package recovers
the full physical specification (18 parameters for P = 3) from one observed
pattern with no enumeration -- no sign combinations, no frequency-triple
search, no angle grids -- and certifies every answer: tight per-parameter
error bounds on success, quantitative impossibility statements on failure.

Public API
----------
extract_speeds(pattern, dt, n_gen=3)   signed speeds + diagnostics
solve9(pattern, fixed9)                9-D protocol (geometry known)
solve18(pattern)                       full 18-D, nothing assumed known
certify_success(x18, pattern, rmask)   per-parameter 3-sigma+gap bounds
spectral_certificate(pattern, N, info) failure certificate (Fisher)
battery_cases(...), vec2pat(...)       standard battery / forward bridge

Reproducibility note: pin BLAS threads (OMP/MKL/OPENBLAS_NUM_THREADS=1)
BEFORE importing numpy -- multithreaded eig/svd are not bitwise
reproducible and the CLEAN greedy amplifies the difference on
boundary cases. The experiments/ scripts do this in their headers.

Method and validation: DIARY.md (2026-07-17/18), paper/REWRITE_PLAN.md,
experiments/assumptions.py (A1-A8).
"""
from .model import (P_DEFAULT, T_PTS, T_OBS, DT, FS, SRC, THK, N_PAR, NAMES,
                    LO, HI, RG, canon, vec2pat, pat_P, battery_cases,
                    battery_cases_P, case_stats, case_at, truth_margins)
from .lattice import (SPEED_MAX, SPEED_MIN, matrix_pencil, kset, lattice_fit,
                      model_eval, parsimony, coverage_score, fundamentals)
from .spectral import extract_speeds, deglitch_mask, clean_lines, select_bases
from .angles import (wrap, line_amp_at, proj_phases, calibrate_ax,
                     invert_cubic, angle_init, nominal_rest)
from .solve import solve9, solve18, trf, MSE_OK
from .certify import certify_success, spectral_fisher, spectral_certificate
